apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: matrices.matrix.com
spec:
  group: matrix.com
  names:
    kind: Matrix
    listKind: MatrixList
    plural: matrices
    singular: matrix
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
