apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: matrix-operator
  template:
    metadata:
      labels:
        name: matrix-operator
    spec:
      serviceAccountName: matrix-operator
      containers:
        - name: matrix-operator
          # Replace this with the built image name
          image: quay.io/anrastog/matrix-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "matrix-operator"
